command = "hyprctl dispatch exec '[float;center;size 1200 800] chromium --new-window'"

[[entries]]
default = true
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[entries]]
name = "GitHub (Google)"
url = "https://www.google.com/search?q=site:github.com+%TERM%"
