command = "omarchy-launch-webapp"
always_show_default = true
engines_as_actions = false

[[entries]]
default = true
name = "GitHub"
url = "https://www.google.com/search?q=site:github.com+%TERM%"

[[entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"
